### ISSUE TITLE
No NSObject rootclass required

### ISSUE THREAD

**Issue by wujichao** [Patrick-Kladek/pkDebugFramework#2]
You can try something like this on iOS.
```
#import "NSObject+Hack.h"
#import <CocoaTouchDebugKit/CocoaTouchDebugKit.h>

@implementation NSObject (Hack)

- (id)debugQuickLookObject
{
	// NOTE: There is a bug in Xcode which will show a empty view in QuickLook when running on an iOS target. To work around this we simply return an UIImage
	return [[CocoaDebugView debugViewWithAllPropertiesOfObject:self includeSuperclasses:YES] imageRepresentation];
}

@end
```
Reference: [Quick Look Debugging With UIView](http://benscheirman.com/2014/03/quick-look-debugging-with-uiview/)

**Comment by Patrick-Kladek** [comment]
NSObject rootclass required means that in your class hierarchy NSObject its required.
e.g: MyDocument : NSDocument : **NSObject** will work (most cases are like this)
but: MyClass : MyCustomRootClass will not. (maybe C++)

I also thought on adding a category to NSObject to enable CocoaDebugView on all classes that
inherit from NSObject. However when you implement -debugQuickLookObject somewhere else 
it will result in undefined behavior. If you do want to use the category I would suggest to ignore
superclasses otherwise you get huge quickLook views.
`[CocoaDebugView debugViewWithAllPropertiesOfObject:self includeSuperclasses:NO]`

**Comment by wujichao** [comment]
Sorry, i did misunderstood your meaning. 
The advice you suggested is really helpful, thx.
